services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    environment:
      - HUGO_ENVIRONMENT=development
    volumes:
      - .:/src
      - /src/node_modules
      - /src/resources
      - hugo_cache:/tmp/hugo_cache

  update:
    build: .
    profiles: ["update"]
    entrypoint: bash -c "hugo mod tidy && hugo mod npm pack && npm update"
    volumes:
      - .:/src
      - hugo_cache:/tmp/hugo_cache

volumes:
  hugo_cache: