services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    environment:
      - HUGO_ENVIRONMENT=development
    volumes:
      - .:/src
      - /src/node_modules
      - /src/resources
      - hugo_cache:/tmp/hugo_cache

volumes:
  hugo_cache: